Fix runtime error:
"java.lang.NoSuchMethodError: No such DSL method 'checkoutRepo' found"

(cherry picked from commit 26b7e69a9435652f2970d78d2afccf42d24dff5c)